# Пайплайн для сборки релизного подписанного билда.
# Нужен для выгрузки сборки в Firebase App Distribution.
name: Flutter TAG

# - Будет запущен на пуш тэга.
on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: "12.x"

      - uses: subosito/flutter-action@v1
        with:
          channel: "stable"

      - run: echo $KEY_JKS | base64 -d > android/keystore/release_key_store.jks
        env:
          KEY_JKS: ${{ secrets.KEY_JKS }}

      - run: sh ./scripts/pub/flutter_pub_get.sh

      - run: sh ./scripts/analyze/flutter_analyze.sh

      - run: sh ./scripts/test/flutter_test.sh

      - run: sh ./scripts/build/android/flutter_build_apk_prod.sh
        env:
          STORE_PASSWORD: ${{ secrets.STORE_PASSWORD }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          STORE_FILE: ${{ secrets.STORE_FILE }}

      - uses: actions/upload-artifact@v1
        with:
          name: release-apk
          path: build/app/outputs/apk/prod/release/app-prod-release.apk
      
      - name: Upload artifact to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{ secrets.FIREBASE_ANDROID_PROD_APP_ID }}
          token: ${{ secrets.FIREBASE_TOKEN }}
          groups: testers
          file: build/app/outputs/apk/prod/release/app-prod-release.apk
          debug: true
